---
apiVersion: influxdb.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  endpoint: http://localhost:8086
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: influxdb-token
      key: authToken
