apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-azure
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane/provider-azure
    meta.crossplane.io/license: Apache-2.0
    friendly-name.meta.crossplane.io: Provider InfluxDB
    friendly-group-name.meta.crossplane.io/influxdb.crossplane.io: InfluxDB
    friendly-kind-name.meta.crossplane.io/organizations.azure.crossplane.io: Organization
spec:
  controller:
    image: crossplane/provider-influxdb-controller:VERSION
